// AUTO-GENERATED by vue-zero scan — do not edit
import r0 from './routes/auth.js'
import r1 from './routes/gallery.js'
import r2 from './routes/members.js'
import r3 from './routes/stats.js'
import r4 from './routes/users.js'

export default function register(app) {
  app.route('/api/auth', r0)
  app.route('/api/gallery', r1)
  app.route('/api/members', r2)
  app.route('/api/stats', r3)
  app.route('/api/users', r4)
}
